/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cities */
        get: operations["list_cities_api_v1_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{city_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get City */
        get: operations["get_city_api_v1_cities__city_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aoi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Aois */
        get: operations["list_aois_api_v1_aoi_get"];
        put?: never;
        /** Create Aoi */
        post: operations["create_aoi_api_v1_aoi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aoi/{aoi_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Aoi */
        get: operations["get_aoi_api_v1_aoi__aoi_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode */
        get: operations["geocode_api_v1_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/heat/{city_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heat Layer */
        get: operations["heat_layer_api_v1_heat__city_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/heat/{city_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heat Summary */
        get: operations["heat_summary_api_v1_heat__city_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/heat/{city_id}/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect Cell
         * @description Pixel inspector: coordinates, values, and full provenance per cell.
         */
        get: operations["inspect_cell_api_v1_heat__city_id__cell_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-sources/{aoi_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Sources */
        get: operations["data_sources_api_v1_data_sources__aoi_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotspots/{city_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hotspots */
        get: operations["list_hotspots_api_v1_hotspots__city_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotspots/{city_id}/{hotspot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hotspot */
        get: operations["get_hotspot_api_v1_hotspots__city_id___hotspot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotspots/{city_id}/{hotspot_id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain Hotspot
         * @description Driver explanation for one hotspot.
         *
         *     Served from the trained model artifact via exact tree SHAP when
         *     available; otherwise the demo feature contributions with explicit
         *     LOW-confidence caveats. Never presented as causal effects.
         */
        get: operations["explain_hotspot_api_v1_hotspots__city_id___hotspot_id__explanation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_v1_models__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}/validity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Validity */
        get: operations["model_validity_api_v1_models__model_id__validity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_api_v1_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_v1_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{scenario_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resimulate */
        post: operations["resimulate_api_v1_scenarios__scenario_id__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Scenarios */
        post: operations["compare_scenarios_api_v1_scenarios_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Optimization */
        post: operations["run_optimization_api_v1_optimization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_optimization__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/{run_id}/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Solutions */
        get: operations["get_solutions_api_v1_optimization__run_id__solutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rag Query */
        post: operations["rag_query_api_v1_rag_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rag Sources */
        get: operations["rag_sources_api_v1_rag_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rag Recommendations */
        post: operations["rag_recommendations_api_v1_rag_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/recommendations/{rec_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommendation */
        get: operations["get_recommendation_api_v1_rag_recommendations__rec_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{aoi_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Availability */
        get: operations["availability_api_v1_history__aoi_id__availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{aoi_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_api_v1_history__aoi_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{aoi_id}/frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frame */
        get: operations["frame_api_v1_history__aoi_id__frame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{aoi_id}/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeseries Ep */
        get: operations["timeseries_ep_api_v1_history__aoi_id__timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{aoi_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Season-matched A/B comparison (spec §116).
         *
         *     Refuses comparisons across non-matching seasons unless explicitly
         *     acknowledged, because a January-vs-June comparison says more about
         *     seasons than about change.
         */
        post: operations["compare_api_v1_history__aoi_id__compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/satellites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Satellites */
        get: operations["list_satellites_api_v1_satellites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/satellites/{mission}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mission */
        get: operations["get_mission_api_v1_satellites__mission__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/{aoi_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis_api_v1_analysis__aoi_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/job/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_v1_analysis_job__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorer/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Source */
        get: operations["resolve_source_api_v1_explorer_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explorer/auto-resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auto Resolution
         * @description AUTO RESOLUTION: grid sized to AOI area and limiting source (spec §159).
         */
        get: operations["auto_resolution_api_v1_explorer_auto_resolution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AOI */
        AOI: {
            /** Aoi Id */
            aoi_id: string;
            /** Name */
            name?: string | null;
            /** Geometry */
            geometry: Record<string, never>;
            /** Centroid */
            centroid: number[];
            /** Bounding Box */
            bounding_box: number[];
            /** Country */
            country?: string | null;
            /** Region */
            region?: string | null;
            /** City */
            city?: string | null;
            /** Area Km2 */
            area_km2: number;
            /** Requested Resolution */
            requested_resolution?: number | null;
            /** Created At */
            created_at: string;
            /**
             * Scenario Type
             * @default DEMO
             */
            scenario_type: string;
        } & {
            [key: string]: unknown;
        };
        /** AOICreate */
        AOICreate: {
            /** Name */
            name?: string | null;
            /** Geometry */
            geometry?: Record<string, never> | null;
            /**
             * Bbox
             * @description [w, s, e, n]
             */
            bbox?: number[] | null;
            /**
             * Center
             * @description [lat, lon]
             */
            center?: number[] | null;
            /** Radius Km */
            radius_km?: number | null;
            /** Country */
            country?: string | null;
            /** Region */
            region?: string | null;
            /** City */
            city?: string | null;
            /** Requested Resolution */
            requested_resolution?: number | null;
        };
        /** City */
        City: {
            /** City Id */
            city_id: string;
            /** Name */
            name: string;
            /** Country */
            country: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Bounding Box */
            bounding_box: number[];
            /** Timezone */
            timezone: string;
            /** Default Zoom */
            default_zoom: number;
            /** Available Datasets */
            available_datasets: string[];
        } & {
            [key: string]: unknown;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Date A */
            date_a: string;
            /** Date B */
            date_b: string;
            /**
             * Mode
             * @default swipe
             * @enum {string}
             */
            mode: "swipe" | "opacity" | "split" | "difference";
        };
        /** Envelope[AOI] */
        Envelope_AOI_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["AOI"] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Envelope[City] */
        Envelope_City_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["City"] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Envelope[HeatSummary] */
        Envelope_HeatSummary_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["HeatSummary"] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Envelope[Hotspot] */
        Envelope_Hotspot_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["Hotspot"] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Envelope[OptimizationRunData] */
        Envelope_OptimizationRunData_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["OptimizationRunData"] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Envelope[ScenarioRecord] */
        Envelope_ScenarioRecord_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["ScenarioRecord"] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Envelope[ScenarioResponseData] */
        Envelope_ScenarioResponseData_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data?: components["schemas"]["ScenarioResponseData"] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Envelope[list[City]] */
        Envelope_list_City__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data?: components["schemas"]["City"][] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** Envelope[list[Hotspot]] */
        Envelope_list_Hotspot__: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Data */
            data?: components["schemas"]["Hotspot"][] | null;
            /** Meta */
            meta?: Record<string, never>;
            error?: components["schemas"]["ErrorBody"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatSummary */
        HeatSummary: {
            /** Mean Lst */
            mean_lst: number;
            /** Min Lst */
            min_lst: number;
            /** Max Lst */
            max_lst: number;
            /** P95 Lst */
            p95_lst: number;
            /** Hot Cells */
            hot_cells: number;
            /** Extreme Cells */
            extreme_cells: number;
            /** Mean Ndvi */
            mean_ndvi: number;
            /** Mean Ndbi */
            mean_ndbi: number;
            /** Population Total */
            population_total: number;
            /** Hotspot Count */
            hotspot_count: number;
            /** Acquisition Time */
            acquisition_time: string;
            /**
             * Scenario Type
             * @default DEMO
             */
            scenario_type: string;
        } & {
            [key: string]: unknown;
        };
        /** Hotspot */
        Hotspot: {
            /** Hotspot Id */
            hotspot_id: string;
            /** Name */
            name: string;
            /** Intensity */
            intensity: string;
            cell: components["schemas"]["HotspotCell"];
            /** Mean Lst */
            mean_lst: number;
            /** Peak Lst */
            peak_lst: number;
            /** Population Exposed */
            population_exposed: number;
            /** Drivers */
            drivers?: Record<string, never>[];
            /**
             * Scenario Type
             * @default DEMO
             */
            scenario_type: string;
        } & {
            [key: string]: unknown;
        };
        /** HotspotCell */
        HotspotCell: {
            /** Cell Index */
            cell_index: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Lst */
            lst: number;
        } & {
            [key: string]: unknown;
        };
        /** OptimizationRecommendation */
        OptimizationRecommendation: {
            /** Interventions */
            interventions: string[];
            /** Mean Cooling Deg C */
            mean_cooling_deg_c: number;
            /** Cost Usd */
            cost_usd: number;
            /** Population Benefited */
            population_benefited: number;
            /** Feasibility */
            feasibility: number;
            /** Solution Id */
            solution_id: string;
            /**
             * Scenario Type
             * @default DEMO
             */
            scenario_type: string;
        } & {
            [key: string]: unknown;
        };
        /** OptimizationRequest */
        OptimizationRequest: {
            /**
             * Budget Usd
             * @default 4000000
             */
            budget_usd: number;
            /**
             * Climate
             * @default semi-arid
             */
            climate: string;
            /**
             * Pop Size
             * @default 80
             */
            pop_size: number;
            /**
             * N Gen
             * @default 60
             */
            n_gen: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** OptimizationRunData */
        OptimizationRunData: {
            /** Run Id */
            run_id: string;
            /** N Solutions */
            n_solutions: number;
            /** Algorithm */
            algorithm: string;
            recommendation: components["schemas"]["OptimizationRecommendation"];
            /**
             * Scenario Type
             * @default DEMO
             */
            scenario_type: string;
        } & {
            [key: string]: unknown;
        };
        /** RagQuery */
        RagQuery: {
            /** Question */
            question: string;
            /** Aoi Id */
            aoi_id?: string | null;
            /** Hotspot Id */
            hotspot_id?: string | null;
            /**
             * Climate
             * @default semi-arid
             */
            climate: string;
            /** Candidate Interventions */
            candidate_interventions?: string[] | null;
        };
        /** ScenarioCreate */
        ScenarioCreate: {
            /**
             * Tree Canopy Percent
             * @default 0
             */
            tree_canopy_percent: number;
            /**
             * Cool Roof Percent
             * @default 0
             */
            cool_roof_percent: number;
            /**
             * Green Roof Percent
             * @default 0
             */
            green_roof_percent: number;
            /**
             * Albedo Delta
             * @default 0
             */
            albedo_delta: number;
            /**
             * Water Area Delta
             * @default 0
             */
            water_area_delta: number;
            /**
             * Climate
             * @default semi-arid
             */
            climate: string;
            /** Name */
            name?: string | null;
            /** Aoi Id */
            aoi_id?: string | null;
        };
        /** ScenarioRecord */
        ScenarioRecord: {
            /** Scenario Id */
            scenario_id: string;
            /** Name */
            name?: string | null;
            /** Params */
            params: Record<string, never>;
            result: components["schemas"]["ScenarioResult"];
        } & {
            [key: string]: unknown;
        };
        /** ScenarioResponseData */
        ScenarioResponseData: {
            /** Scenario Id */
            scenario_id: string;
            summary: components["schemas"]["ScenarioSummary"];
            /** Provenance */
            provenance?: Record<string, never>;
            /**
             * Scenario Type
             * @default DEMO
             */
            scenario_type: string;
            result?: components["schemas"]["ScenarioResult"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ScenarioResult */
        ScenarioResult: {
            /**
             * Scenario Type
             * @default DEMO
             */
            scenario_type: string;
            /** Simulated Lst */
            simulated_lst: number[];
            /** Delta Lst */
            delta_lst: number[];
            summary: components["schemas"]["ScenarioSummary"];
            /** Provenance */
            provenance?: Record<string, never>;
            /**
             * Climate
             * @default semi-arid
             */
            climate: string;
            /** Params */
            params?: Record<string, never>;
        } & {
            [key: string]: unknown;
        };
        /** ScenarioSummary */
        ScenarioSummary: {
            /** Mean Delta Lst */
            mean_delta_lst: number;
            /** Max Cooling */
            max_cooling: number;
            /** Mean Simulated Lst */
            mean_simulated_lst: number;
            /** Min Simulated Lst */
            min_simulated_lst: number;
            /** Max Simulated Lst */
            max_simulated_lst: number;
            /** Population Benefited */
            population_benefited: number;
            /** Population Pct */
            population_pct: number;
            /** Hotspot Count Before */
            hotspot_count_before: number;
            /** Hotspot Count After */
            hotspot_count_after: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /**
             * Scenario Type
             * @default DEMO
             */
            scenario_type: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_cities_api_v1_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_City__"];
                };
            };
        };
    };
    get_city_api_v1_cities__city_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_City_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_aois_api_v1_aoi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    create_aoi_api_v1_aoi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AOICreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AOI_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aoi_api_v1_aoi__aoi_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AOI_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_api_v1_geocode_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heat_layer_api_v1_heat__city_id__get: {
        parameters: {
            query?: {
                layer?: string;
            };
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heat_summary_api_v1_heat__city_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HeatSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_cell_api_v1_heat__city_id__cell_get: {
        parameters: {
            query: {
                index: number;
            };
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_sources_api_v1_data_sources__aoi_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hotspots_api_v1_hotspots__city_id__get: {
        parameters: {
            query?: {
                method?: string;
            };
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_Hotspot__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hotspot_api_v1_hotspots__city_id___hotspot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
                hotspot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Hotspot_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_hotspot_api_v1_hotspots__city_id___hotspot_id__explanation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
                hotspot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_model_api_v1_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_validity_api_v1_models__model_id__validity_get: {
        parameters: {
            query?: {
                climate?: string;
                latitude?: number;
            };
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scenario_api_v1_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScenarioResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_api_v1_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScenarioRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resimulate_api_v1_scenarios__scenario_id__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScenarioResponseData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_scenarios_api_v1_scenarios_compare_post: {
        parameters: {
            query: {
                a_id: string;
                b_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_optimization_api_v1_optimization_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_OptimizationRunData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_optimization__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_solutions_api_v1_optimization__run_id__solutions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rag_query_api_v1_rag_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rag_sources_api_v1_rag_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    rag_recommendations_api_v1_rag_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendation_api_v1_rag_recommendations__rec_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rec_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    availability_api_v1_history__aoi_id__availability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_v1_history__aoi_id__timeline_get: {
        parameters: {
            query?: {
                variable?: string;
                start?: number;
                end?: number;
            };
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frame_api_v1_history__aoi_id__frame_get: {
        parameters: {
            query: {
                year: number;
                month?: number;
                day?: number;
                variable?: string;
                max_cloud?: number;
            };
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeseries_ep_api_v1_history__aoi_id__timeseries_get: {
        parameters: {
            query?: {
                resolution?: string;
            };
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_history__aoi_id__compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_satellites_api_v1_satellites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_mission_api_v1_satellites__mission__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_analysis_api_v1_analysis__aoi_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_api_v1_analysis_job__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_source_api_v1_explorer_resolve_get: {
        parameters: {
            query?: {
                variable?: string;
                date?: string;
                max_cloud?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_resolution_api_v1_explorer_auto_resolution_get: {
        parameters: {
            query: {
                area_km2: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
